namespace EcomBackend.Application.DTOs;

public record ProductDto(
    Guid Id,
    string Name,
    decimal Price,
    string Description,
    string ShortDescription,
    string Category,
    string Image,
    List<string> Images,
    bool BestSeller,
    bool IsPromoted,
    bool IsActive,
    int Stock,
    string Marque,
    string Modele,
    string Dimension,
    string Genre,
    string Freinage,
    string SystemeD,
    string DimensionCaisseChargement,
    string BoiteVitesse,
    string SpecificationTechnique,
    string CapaciteCharge,
    string TypeCarburant,
    string Etat,
    DateTime CreatedAt
);

public record CreateProductDto(
    string Name,
    decimal Price,
    string Description,
    string ShortDescription,
    string Category,
    string Image,
    List<string>? Images,
    bool BestSeller,
    bool IsPromoted,
    bool IsActive,
    int Stock,
    string Marque,
    string Modele,
    string Dimension,
    string Genre,
    string Freinage,
    string SystemeD,
    string DimensionCaisseChargement,
    string BoiteVitesse,
    string SpecificationTechnique,
    string CapaciteCharge,
    string TypeCarburant,
    string Etat
);

public record UpdateProductDto(
    string Name,
    decimal Price,
    string Description,
    string ShortDescription,
    string Category,
    string Image,
    List<string>? Images,
    bool BestSeller,
    bool IsPromoted,
    bool IsActive,
    int Stock,
    string Marque,
    string Modele,
    string Dimension,
    string Genre,
    string Freinage,
    string SystemeD,
    string DimensionCaisseChargement,
    string BoiteVitesse,
    string SpecificationTechnique,
    string CapaciteCharge,
    string TypeCarburant,
    string Etat
);
